[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.skip_processing]
  - "*.js"
  - "*.css"
  - "*.html"
  - "*.png"
  - "*.jpg"
  - "*.gif"
  - "*.ico"
  - "*.svg"
  - "*.woff"
  - "*.woff2"
  - "*.ttf"
  - "*.eot"
  - "*.json"
  - "*.map" 