[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  included_files = ["package.json", "package-lock.json"]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
   atus = 200

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Branch-specific settings
[context.production]
  command = "npm run build"
  publish = "dist"

[context.develop]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "development" }