[build]
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[scheduled]]
  function = "process-notifications"
  schedule = "* * * * *" 